import { lazy } from "react";

export const icons = {
  Add: lazy(() => import("./assets/add.svg?react")),
  Analytics: lazy(() => import("./assets/analytics.svg?react")),
  Apps: lazy(() => import("./assets/apps.svg?react")),
  ArrowLeft: lazy(() => import("./assets/arrow-left.svg?react")),
  ArrowRight: lazy(() => import("./assets/arrow-right.svg?react")),
  ArrowUp: lazy(() => import("./assets/arrow-up.svg?react")),
  ArrowDown: lazy(() => import("./assets/arrow-down.svg?react")),
  Attention: lazy(() => import("./assets/attention.svg?react")),
  Bookmark: lazy(() => import("./assets/bookmark.svg?react")),
  Check: lazy(() => import("./assets/check.svg?react")),
  Close: lazy(() => import("./assets/close.svg?react")),
  Download: lazy(() => import("./assets/download.svg?react")),
  Hashtag: lazy(() => import("./assets/hashtag.svg?react")),
  Info: lazy(() => import("./assets/info.svg?react")),
  Layout: lazy(() => import("./assets/layout.svg?react")),
  Menu: lazy(() => import("./assets/menu.svg?react")),
  Pause: lazy(() => import("./assets/pause.svg?react")),
  PieChart: lazy(() => import("./assets/pie-chart.svg?react")),
  Play: lazy(() => import("./assets/play.svg?react")),
  Remove: lazy(() => import("./assets/remove.svg?react")),
  Settings: lazy(() => import("./assets/settings.svg?react")),
  Upload: lazy(() => import("./assets/upload.svg?react")),
};
